export const ADMIN_ROUTE = "/admin";
export const LOGIN_ROUTE = "/login";
export const REGISTRATION_ROUTE = "/registration";
export const MAIN_ROUTE = "/";
export const ABOUT_ROUTE = "/about";
export const FAQ_ROUTE = "/faq";
export const WARRANTY_ROUTE = "/warranty";
export const CREATE_HARDWARE_ROUTE = "create/hardware";
export const CREATE_FOREIGN_ROUTE = "create/foreign";
export const DELETE_HARDWARE_ROUTE = "delete/hardware";
export const DELETE_FOREIGN_ROUTE = "delete/foreign";
export const HARDWARE_ROUTE = "/:type/:id";

export const ITEMS_LIST = [
    { type: "processor", name: "Процессор", require: true },
    { type: "motherboard", name: "Материнская плата", require: true },
    { type: "ram", name: "Оперативная память", require: true },
    { type: "case", name: "Корпус", require: true },
    { type: "power", name: "Блок питания", require: true },
    { type: "videocard", name: "Видеокарта", require: false },
    { type: "cooler", name: "Кулер", require: false },
    { type: "storage", name: "Хранилище", require: false },
];

export const FOREIGNS_LIST = [
    { type: "StorageInterface", name: "Интерфейс хранилища" },
    { type: "FormFactor", name: "Форм-фактор материнской платы" },
    { type: "RamType", name: "Тип оперативной памяти" },
    { type: "Socket", name: "Сокет" },
    {
        type: "CaseFormFactor",
        name: "Форм-фактор материнских плат корпуса",
        relations: { CaseId: "Case", FormFactorId: "FormFactor" },
    },
    { type: "CoolerSocket", name: "Сокеты кулера", relations: { CoolerId: "Cooler", SocketId: "Socket" } },
];

export const FILTER_TYPES = {
    interval: "interval",
    selector: "selector",
    selectorWithForeign: "selectorWithForeign",
    selectorWithManyForeign: "selectorWithManyForeign",
};
export const INPUT_TYPES = {
    text: "text",
    number: "number",
    select: "select",
    file: "file",
    date: "date",
};
export const HARDWARE_SPECIFICATIONS = {
    processor: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        model: { title: "Линейка", inputType: INPUT_TYPES.text },
        SocketId: { title: "Сокет", inputType: INPUT_TYPES.select, foreign: "Socket" },
        speed: { title: "Тактовая частота", inputType: INPUT_TYPES.number, sign: "Мгц" },
        cores: { title: "Ядра", inputType: INPUT_TYPES.number },
        threads: { title: "Потоки", inputType: INPUT_TYPES.number },
        tdp: { title: "Тепловыделение", inputType: INPUT_TYPES.number, sign: "Вт" },
        nanometers: { title: "Техпроцесс", inputType: INPUT_TYPES.number, sign: "Нм" },
        cacheL1: { title: "Кеш L1", inputType: INPUT_TYPES.text },
        cacheL2: { title: "Кеш L2", inputType: INPUT_TYPES.text },
        cacheL3: { title: "Кеш L3", inputType: INPUT_TYPES.text },
        isIntegratedVideo: { title: "Наличие встроенного графического процессора", inputType: INPUT_TYPES.text },
        integratedVideoName: { title: "Встроенный графический процессор", inputType: INPUT_TYPES.text },
        postType: { title: "Тип поставки", inputType: INPUT_TYPES.text },
    },
    motherboard: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        SocketId: { title: "Сокет", inputType: INPUT_TYPES.select, foreign: "Socket" },
        chipset: { title: "Чипсет", inputType: INPUT_TYPES.text },
        maxRamAmount: { title: "Количество слотов памяти", inputType: INPUT_TYPES.number },
        m2Amount: { title: "Количество слотов M2", inputType: INPUT_TYPES.number },
        cpuPins: { title: "Питание процессора", inputType: INPUT_TYPES.text },
        FormFactorId: { title: "Форм-фактор", inputType: INPUT_TYPES.select, foreign: "FormFactor" },
        RamTypeId: { title: "Тип памяти", inputType: INPUT_TYPES.select, foreign: "RamType" },
        StorageInterfaceId: {
            title: "Интерфейс подключения хранилища",
            inputType: INPUT_TYPES.select,
            foreign: "StorageInterface",
        },
    },
    ram: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        formfactor: { title: "Форм-фактор", inputType: INPUT_TYPES.text },
        RamTypeId: { title: "Тип памяти", inputType: INPUT_TYPES.select, foreign: "RamType" },
        memoryVolume: { title: "Объём памяти", inputType: INPUT_TYPES.number, sign: "Гб" },
        oneMemoryVolume: { title: "Объём одного модуля", inputType: INPUT_TYPES.number, sign: "Гб" },
        moduleAmount: { title: "Количество модулей", inputType: INPUT_TYPES.number },
        clockRate: { title: "Тактовая частота", inputType: INPUT_TYPES.number, sign: "Мгц" },
        bandwidth: { title: "Пропускная способность", inputType: INPUT_TYPES.number },
        casLatency: { title: "CAS Latency", inputType: INPUT_TYPES.number },
        xmp: { title: "Наличие XMP", inputType: INPUT_TYPES.text },
        height: { title: "Высота модуля", inputType: INPUT_TYPES.number, sign: "Мм" },
        voltage: { title: "Вольтаж", inputType: INPUT_TYPES.number, sign: "Вт" },
    },
    case: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        typefactor: { title: "Типоразмер", inputType: INPUT_TYPES.text },
        FormFactorId: {
            title: "Форм-фактор материнской платы",
            inputType: INPUT_TYPES.select,
            foreign: "FormFactor",
        },
        maxCoolerHeight: {
            title: "Максимальная высота кулера",
            inputType: INPUT_TYPES.number,
        },
        maxVideocardHeight: {
            title: "Максимальная длина видеокарты",
            inputType: INPUT_TYPES.number,
        },
        weight: { title: "Вес", inputType: INPUT_TYPES.number },
        sizes: { title: "Размеры", inputType: INPUT_TYPES.text },
        max25Inch: { title: "Количество отсеков 2.5", inputType: INPUT_TYPES.number },
        max35Inch: { title: "Количество отсеков 3.5", inputType: INPUT_TYPES.number },
        maxFans: { title: "Максимальное количество вентиляторов", inputType: INPUT_TYPES.number },
        fansSize: { title: "Размер вентиляторов", inputType: INPUT_TYPES.number },
        color: { title: "Цвет", inputType: INPUT_TYPES.text },
    },
    power: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        power: { title: "Мощность", inputType: INPUT_TYPES.number },
        standart: { title: "Стандарт", inputType: INPUT_TYPES.text },
        fanSize: { title: "Размер вентилятора", inputType: INPUT_TYPES.number },
        certificate: { title: "Сертификат", inputType: INPUT_TYPES.text },
        motherboardPinType: { title: "Тип питания материнской платы", inputType: INPUT_TYPES.text },
        cpuPinType: { title: "Тип питания CPU", inputType: INPUT_TYPES.text },
        pciePinType: { title: "Тип питания PCI-E", inputType: INPUT_TYPES.text },
        idePinType: { title: "Тип питания IDE", inputType: INPUT_TYPES.text },
        sataPinType: { title: "Тип питания SATA", inputType: INPUT_TYPES.text },
        cpuPinAmount: { title: "Количество разъёмов CPU", inputType: INPUT_TYPES.number },
        pciePinAmount: { title: "Количество разъёмов PCI-E", inputType: INPUT_TYPES.number },
        idePinAmount: { title: "Количество разъёмов IDE", inputType: INPUT_TYPES.number },
        sataPinAmount: { title: "Количество разъёмов SATA", inputType: INPUT_TYPES.number },
    },
    videocard: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        processorBrand: { title: "Производитель видеопроцессора", inputType: INPUT_TYPES.text },
        interface: { title: "Интерфейс", inputType: INPUT_TYPES.text },
        fanAmount: { title: "Количество вентиляторов", inputType: INPUT_TYPES.number },
        connectors: { title: "Разъемы вывода", inputType: INPUT_TYPES.text },
        nanometers: { title: "Техпроцесс", inputType: INPUT_TYPES.number },
        clockSpeed: { title: "Тактовая частота", inputType: INPUT_TYPES.number },
        maxResolution: { title: "Максимальное разрешение", inputType: INPUT_TYPES.text },
        maxMonitors: { title: "Максимум мониторов", inputType: INPUT_TYPES.text },
        width: { title: "Длина", inputType: INPUT_TYPES.number },
        size: { title: "Размеры", inputType: INPUT_TYPES.text },
        weight: { title: "Вес", inputType: INPUT_TYPES.number },
        powerPin: { title: "Разъём питания", inputType: INPUT_TYPES.text },
        power: { title: "Потребление", inputType: INPUT_TYPES.number },
        memorySize: { title: "Объём памяти", inputType: INPUT_TYPES.number },
        memoryType: { title: "Тип памяти", inputType: INPUT_TYPES.text },
        memoryClock: { title: "Пропускная способность памяти", inputType: INPUT_TYPES.number },
    },
    cooler: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        SocketId: {
            title: "Сокет",
            inputType: INPUT_TYPES.select,
            foreign: "Socket",
        },
        maxTdp: { title: "Максимальная рассеиваемая мощность", inputType: INPUT_TYPES.number },
        material: { title: "Материал", inputType: INPUT_TYPES.text },
        height: { title: "Высота", inputType: INPUT_TYPES.number },
        weight: { title: "Вес", inputType: INPUT_TYPES.number },
        fanNoise: { title: "Шум", inputType: INPUT_TYPES.number },
        fanSize: { title: "Размер вентилятора", inputType: INPUT_TYPES.number },
        bearing: { title: "Тип подшипника", inputType: INPUT_TYPES.text },
        fanMinSpeed: { title: "Минимальная скорость вращения", inputType: INPUT_TYPES.number },
        fanMaxSpeed: { title: "Максимальная скорость вращения", inputType: INPUT_TYPES.number },
    },
    storage: {
        name: { title: "Модель", inputType: INPUT_TYPES.text },
        brand: { title: "Производитель", inputType: INPUT_TYPES.text },
        price: { title: "Цена", inputType: INPUT_TYPES.number },
        img: { title: "Изображение", inputType: INPUT_TYPES.file },
        releaseDate: { title: "Дата релиза", inputType: INPUT_TYPES.date },
        type: { title: "Тип накопителя", inputType: INPUT_TYPES.text },
        formfactor: { title: "Форм-фактор", inputType: INPUT_TYPES.number },
        StorageInterfaceId: {
            title: "Интерфейс подключения",
            inputType: INPUT_TYPES.select,
            foreign: "StorageInterface",
        },
        memorySize: { title: "Объём памяти", inputType: INPUT_TYPES.number },
        spindleSpeed: { title: "Скорость вращения шпинделя", inputType: INPUT_TYPES.number },
        readSpeed: { title: "Скорость чтения", inputType: INPUT_TYPES.number },
        writeSpeed: { title: "Скорость записи", inputType: INPUT_TYPES.number },
        tbw: { title: "Ресурс записи", inputType: INPUT_TYPES.number },
    },
};
