const userRoles = {
    ADMIN: "ADMIN",
    USER: "USER",
};
const hardwares = ["Case", "Cooler", "Motherboard", "Power", "Processor", "Ram", "Storage", "Videocard"];

const FILTER_TYPES = {
    interval: "interval",
    selector: "selector",
};
const FILTER_MODEL_TYPES = {
    processor: {
        name: { title: "Линейка", type: FILTER_TYPES.selector },
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        model: { title: "Модель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        socket: { title: "Сокет", type: FILTER_TYPES.selector },
        speed: { title: "Тактовая частота", type: FILTER_TYPES.interval },
        cores: { title: "Ядра", type: FILTER_TYPES.selector },
        threads: { title: "Потоки", type: FILTER_TYPES.selector },
        tdp: { title: "Тепловыделение", type: FILTER_TYPES.interval },
        nanometers: { title: "Техпроцесс", type: FILTER_TYPES.selector },
        isIntegratedVideo: { title: "Встроенная графика", type: FILTER_TYPES.selector },
        postType: { title: "Тип поставки", type: FILTER_TYPES.selector },
    },
    motherboard: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        socket: { title: "Сокет", type: FILTER_TYPES.selector },
        chipset: { title: "Чипсет", type: FILTER_TYPES.selector },
        formfactor: { title: "Форм-фактор", type: FILTER_TYPES.selector },
        ramType: { title: "Тип памяти", type: FILTER_TYPES.selector },
        maxRamAmount: { title: "Количество слотов памяти", type: FILTER_TYPES.selector },
        m2Amount: { title: "Количество слотов M2", type: FILTER_TYPES.selector },
        cpuPins: { title: "Питание процессора", type: FILTER_TYPES.selector },
    },
    ram: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        formfactor: { title: "Форм-фактор", type: FILTER_TYPES.selector },
        memoryType: { title: "Тип памяти", type: FILTER_TYPES.selector },
        memoryVolume: { title: "Объём памяти", type: FILTER_TYPES.selector },
        oneMemoryVolume: { title: "Объём одного модуля", type: FILTER_TYPES.selector },
        moduleAmount: { title: "Количество модулей", type: FILTER_TYPES.selector },
        clockRate: { title: "Тактовая частота", type: FILTER_TYPES.selector },
        bandwidth: { title: "Пропускная способность", type: FILTER_TYPES.selector },
        casLatency: { title: "CAS Latency", type: FILTER_TYPES.selector },
        xmp: { title: "Наличие XMP", type: FILTER_TYPES.selector },
        height: { title: "Высота модуля", type: FILTER_TYPES.interval },
    },
    case: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        typefactor: { title: "Типоразмер", type: FILTER_TYPES.selector },
        motherboardFormfactors: { title: "Форм-фактор материнской платы", type: FILTER_TYPES.selector },
        maxCoolerHeight: { title: "Максимальная высота кулера", type: FILTER_TYPES.interval },
        maxVideocardHeight: { title: "Максимальная длина видеокарты", type: FILTER_TYPES.interval },
        weight: { title: "Вес", type: FILTER_TYPES.interval },
        max25Inch: { title: "Количество отсеков 2.5", type: FILTER_TYPES.selector },
        max35Inch: { title: "Количество отсеков 3.5", type: FILTER_TYPES.selector },
        maxFans: { title: "Максимальное количество вентиляторов", type: FILTER_TYPES.selector },
        fansSize: { title: "Размер вентиляторов", type: FILTER_TYPES.selector },
        color: { title: "Цвет", type: FILTER_TYPES.selector },
    },
    power: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        power: { title: "Мощность", type: FILTER_TYPES.interval },
        standart: { title: "Производитель", type: FILTER_TYPES.selector },
        fanSize: { title: "Размер вентилятора", type: FILTER_TYPES.selector },
        certificate: { title: "Сертификат", type: FILTER_TYPES.selector },
        motherboardPinType: { title: "Тип разъёма материнской платы", type: FILTER_TYPES.selector },
        cpuPinType: { title: "Тип питания CPU", type: FILTER_TYPES.selector },
        pciePinType: { title: "Тип питания PCI-E", type: FILTER_TYPES.selector },
        idePinType: { title: "Тип питания IDE", type: FILTER_TYPES.selector },
        sataPinType: { title: "Тип питания SATA", type: FILTER_TYPES.selector },
        cpuPinAmount: { title: "Количество разъёмов CPU", type: FILTER_TYPES.selector },
        pciePinAmount: { title: "Количество разъёмов PCI-E", type: FILTER_TYPES.selector },
        idePinAmount: { title: "Количество разъёмов IDE", type: FILTER_TYPES.selector },
        sataPinAmount: { title: "Количество разъёмов SATA", type: FILTER_TYPES.selector },
    },
    videocard: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        processorBrand: { title: "Производитель видеопроцессора", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        interface: { title: "Интерфейс", type: FILTER_TYPES.selector },
        fanAmount: { title: "Количество вентиляторов", type: FILTER_TYPES.selector },
        connectors: { title: "Разъём", type: FILTER_TYPES.selector },
        nanometers: { title: "Техпроцесс", type: FILTER_TYPES.selector },
        clockSpeed: { title: "Тактовая частота", type: FILTER_TYPES.interval },
        maxResolution: { title: "Максимальное разрешение", type: FILTER_TYPES.selector },
        maxMonitors: { title: "Максимум мониторов", type: FILTER_TYPES.selector },
        size: { title: "Длина", type: FILTER_TYPES.interval },
        weight: { title: "Вес", type: FILTER_TYPES.interval },
        powerPin: { title: "Разъём питания", type: FILTER_TYPES.selector },
        power: { title: "Рекомендуемая мощность", type: FILTER_TYPES.interval },
        memorySize: { title: "Объём памяти", type: FILTER_TYPES.selector },
        memoryType: { title: "Тип памяти", type: FILTER_TYPES.selector },
        memoryClock: { title: "Пропускная способность памяти", type: FILTER_TYPES.interval },
    },
    cooler: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        sockets: { title: "Сокет", type: FILTER_TYPES.selector },
        maxTdp: { title: "Максимальная рассеиваемая мощность", type: FILTER_TYPES.interval },
        material: { title: "Материал", type: FILTER_TYPES.selector },
        height: { title: "Высота", type: FILTER_TYPES.interval },
        weight: { title: "Вес", type: FILTER_TYPES.interval },
        fanNoise: { title: "Шум", type: FILTER_TYPES.interval },
        fanSize: { title: "Размер вентилятора", type: FILTER_TYPES.selector },
        bearing: { title: "Тип подшипника", type: FILTER_TYPES.selector },
    },
    storage: {
        brand: { title: "Производитель", type: FILTER_TYPES.selector },
        price: { title: "Цена", type: FILTER_TYPES.interval },
        type: { title: "Тип накопителя", type: FILTER_TYPES.selector },
        formfactor: { title: "Форм-фактор", type: FILTER_TYPES.selector },
        interface: { title: "Интерфейс", type: FILTER_TYPES.selector },
        memorySize: { title: "Объём памяти", type: FILTER_TYPES.selector },
        spindleSpeed: { title: "Скорость вращения шпинделя", type: FILTER_TYPES.selector },
        readSpeed: { title: "Скорость чтения", type: FILTER_TYPES.interval },
        writeSpeed: { title: "Скорость записи", type: FILTER_TYPES.interval },
    },
};

module.exports = { userRoles, hardwares, FILTER_MODEL_TYPES, FILTER_TYPES };
